# Source: superset/templates/supersetdb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  name: {{ .Values.secret.name }}
stringData:
  database-name: {{ .Values.secret.database.name }}
  database-password: {{ .Values.secret.database.password }}
  database-user: {{ .Values.secret.database.user }}
