kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    template: redis-persistent-template
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    name: redis