kind: Secret
apiVersion: v1
metadata:
  name: kc-admin-creds
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: Vkp0Mk1RdVVrcnJnOTI=
  HOSTULR: YXBpLm9zYy1jbDQuYXBwcy5vcy1jbGltYXRlLm9yZw==
type: Opaque
