kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
stringData:
  POSTGRESQL_ADMIN_PASSWORD: Ba1vdsgcyMuVcX
  POSTGRESQL_DATABASE: keycloak
  POSTGRESQL_PASSWORD: EfwcG3Ui6QYDSC
  POSTGRESQL_USER: keycloak