kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.PostgresSelector}}-secret
stringData:
  PostgresqlAdminPassword: {{ .Values.global.PostgresqlAdminPassword}}
  PostgresqlDatabase: {{ .Values.global.PostgresqlDatabase}}
  PostgresqlPassword: {{ .Values.global.PostgresqlPassword}}   
  PostgresqlUser: {{ .Values.global.PostgresqlUser}}
type: {{ .Values.global.SecretType}}