---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-argo-cd
  namespace: datamesh-ci-cd
spec:
  destination:
    namespace: datamesh-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/opendatahub-io-contrib/datamesh-platform.git
    path: development/airflow/kustomize/overlays/development
    targetRevision: main
    # plugin:
    #   name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - ServerSideApply=true