kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.global.HmsSelector}}-service
spec:
  ports:
    - protocol: {{ .Values.service.protocol}}
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy}}
  type: {{ .Values.service.type}}
  selector:
    app: {{ .Values.global.HmsSelector}}