apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment-manifest/secret-airflow-postgres.yaml
- ./deployment-manifest/deployment-airflow-postgres.yaml
- ./deployment-manifest/secret-dag-deployment.yaml
- ./deployment-manifest/service-postgres.yaml
- ./deployment-manifest/deployment-airflow.yaml
- ./deployment-manifest/service-airflow.yaml
- ./deployment-manifest/route-airflow.yaml
