# Source: superset/templates/supersetdb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: openmetadatadb
    app.kubernetes.io/instance: openmetadata
  name: openmetadatadb
stringData:
  database-name: openmetadatadb
  database-password: redhat123$
  database-user: openmetadatadb
