apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmetadatadb
  labels:
    app.kubernetes.io/name: openmetadatadb
    app.kubernetes.io/instance: openmetadata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"