apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: default-pull-secret
  files:
    - ./deployment-manifest/config.json

resources:

#  - ./deployment-manifest/default-pull-secret.yaml
 - ./deployment-manifest/service-account-default.yaml
 - ./deployment-manifest/service-account-trino.yaml
 - ./deployment-manifest/service-account-superset.yaml


# patches:
# - target:
#     group: rbac.authorization.k8s.io
#     version: v1
#     kind: ClusterRole
#     name: system:image-builder
#   patch: |-
#     - op: add
#       path: /rules/0/resources/0
#       value: "secrets"
# - target:
#     group: ""
#     version: v1
#     kind: ServiceAccount
#     name: default
#   patch: |-
#     - op: add
#       path: /imagePullSecrets/-
#       value:
#         name: default-pull-secret