apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 6 }}