apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment-manifest/deployment-minio.yaml
- ./deployment-manifest/pvc-minio.yaml
- ./deployment-manifest/service-minio.yaml
- ./deployment-manifest/route-minio.yaml