kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hive-postgresql
  labels:
    app.kubernetes.io/instance: hive
    app.kubernetes.io/name: hive-postgresql
    app.kubernetes.io/part-of: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: hive
      app.kubernetes.io/name: hive-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hive
        app.kubernetes.io/name: hive-postgresql
    spec:
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          name: hive-postgresql
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hive-postgresql
                  key: postgresql-admin-password
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: hive-postgresql
                  key: postgresql-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hive-postgresql
                  key: postgresql-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: hive-postgresql
                  key: postgresql-database
          ports:
            - name: tcp-postgresql
              containerPort: 5432
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: hive-data
              mountPath: /var/lib/pgsql/data
          terminationMessagePolicy: File
          # image: 'registry.redhat.io/rhel8/postgresql-13:1-101'
          image: 'quay.io/osclimate/postgresql-13:1-101'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  volumeClaimTemplates:
    - metadata:
        name: hive-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "2Gi"
  updateStrategy:
    type: RollingUpdate