kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.ConfigMap.Catalog.Name }}
data:
  hive.properties: |-
{{ .Values.ConfigMap.Catalog.HiveProperties | indent 4 }}
  iceberg.properties: |-
{{ .Values.ConfigMap.Catalog.IcebergProperties | indent 4 }}
  tpcds.properties: |
{{ .Values.ConfigMap.Catalog.TPCDSProperties | indent 4 }}
  tpch.properties: |
{{ .Values.ConfigMap.Catalog.TPCHProperties | indent 4 }}
