kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.ConfigMap.Coordinator.Name }}
data:
  password-authenticator.properties: |
    password-authenticator.name=file
    file.password-file=/etc/trino/password.db
  group-mapping.properties: |
    admins:admin,jpaulraj
  group-provider.properties: |
    group-provider.name=file
    file.group-file=/etc/trino/group-mapping.properties
  jvm.config: >
    -server

    -agentpath:/usr/lib/trino/bin/libjvmkill.so

    -Xmx8G

    -XX:+UseG1GC

    -XX:G1HeapRegionSize=32M

    -XX:+ExplicitGCInvokesConcurrent

    -XX:+HeapDumpOnOutOfMemoryError

    -XX:+ExitOnOutOfMemoryError

    -XX:-OmitStackTraceInFastThrow

    -XX:ReservedCodeCacheSize=512M

    -XX:PerMethodRecompilationCutoff=10000

    -XX:PerBytecodeRecompilationCutoff=10000

    -Djdk.attach.allowAttachSelf=true

    -Djdk.nio.maxCachedBufferSize=2000000

    -XX:+UnlockDiagnosticVMOptions

    # Reduce starvation of threads by GClocker, recommend to set about the
    number of cpu cores (JDK-8192647)

    -XX:GCLockerRetryAllocationCount=32
  password.db: |-
    admin:$2y$10$rkcRpFHvkflOwkrp3ec65.NBvAOi6MNK4cFhSJfXt2l8KhGuWN0ru
    jpaulraj:$2y$10$YNeVHgzsSe7pHHb6Md5crucOETlZWPW.CjCyt4TsQB7/Wm9ZXINIG
  log.properties: |
    io.trino=INFO
    io.trino.server.security.oauth2=DEBUG
    io.trino.server.ui.OAuth2WebUiAuthenticationFilter=DEBUG
  exchange-manager.properties: |
    exchange-manager.name=filesystem

    exchange.base-directories=/tmp/trino-local-file-system-exchange-manager
  node.properties: |
    node.environment=production
    node.data-dir=/data/trino
    plugin.dir=/usr/lib/trino/plugin
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false 
    discovery-server.enabled=true
    discovery.uri=http://localhost:8080
    http-server.http.port=8080
    http-server.process-forwarded=true
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.https.keystore.path=/etc/trino/keystore/keystore.jks
    http-server.https.keystore.path=/etc/trino/keystore-p12/trino.p12
    http-server.https.keystore.key=redhat2024
    http-server.authentication.allow-insecure-over-http=true
   
