kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.Secret.Name }}
stringData:
  minio-access-key: {{ .Values.Secret.MinioAccessKey }}
  minio-secret-key: {{ .Values.Secret.MinioSecretKey }}
  cluster-host-url: {{ .Values.Secret.ClusterHostUrl }}