apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

secretGenerator:
- name: my-default-pull-secret
  files:
  - .dockerconfigjson=./config.json

patches:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: system:image-builder
  patch: |-
    - op: add
      path: /rules/0/resources/0
      value: "secrets"
- target:
    group: ""
    version: v1
    kind: ServiceAccount
    name: default
  patch: |-
    - op: add
      path: /imagePullSecrets/-
      value:
        name: my-default-pull-secret
