apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datamesh
  namespace: datamesh101-ci-cd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  # verbs: ["get", "list","watch","patch"]
  verbs: ["*"]
# rules:
# - apiGroups:
#   - "*"
#   resources:
#   - "*"
#   verbs:
#   - Get
#   - List
#   - Watch
#   - Patch
---
# For a ClusterRoleBinding (cluster-wide)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: datamesh-ci-cd-argocd-application-controller
  namespace: datamesh101-ci-cd
roleRef:
  kind: ClusterRole
  name: argocd-application-controller-clusterrole
  apiGroup: rbac.authorization.k8s.io
