apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datamesh
  namespace: datamesh-ci-cd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'