apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment-manifest/openmetadatadb-pvc.yaml
- ./deployment-manifest/openmetadatadb-db-secret.yaml
- ./deployment-manifest/deployment-postgres.yaml
- ./deployment-manifest/service-openmetadatadb.yaml

# Non-sso
# - ./deployment-manifest/configmap-openmetadata.yaml
#Non-sso

# SSo
- ./deployment-manifest/configmap-openmetadata-sso.yaml
# SSO
- ./deployment-manifest/deployment-elasticsearch.yaml
- ./deployment-manifest/service-elasticsearch.yaml

# SSo
- ./deployment-manifest/deployment-openmetadata-sso.yaml
# end sso

# start non-sso
# - ./deployment-manifest/deployment-openmetadata.yaml
# end non-sso//
- ./deployment-manifest/service-openmetadata.yaml
- ./deployment-manifest/route-openmetadata.yaml



