kind: Secret
apiVersion: v1
metadata:
  name: superset-env-secret
  labels:
    app.kubernetes.io/instance: superset
    app.kubernetes.io/name: superset
stringData:
  DB_PORT: '5432'
  REDIS_PORT: '6379'
  SUPERSET_SECRET_KEY: 'nBFrzelhM4C/mdLu3av2FFAZUpY2W9UKDciYyqG2N66XHmFUcoxz9pBP'
  DB_HOST: supersetdb
  DB_NAME: supersetdb
  REDIS_HOST: redis
  DB_USER: superset
  DB_PASS: redhat1234
  REDIS_PASSWORD: 7b7k36kBTGdvUE5G